qanda/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import DetailView, ListView
from qanda.models import Department, Course, Professor, Question, Answer

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('qanda.views',
	url(r'^$', 'index'),
	url(r'^(?P<department_id>\d+)/$', 'courses'),
	url(r'^(?P<department_id>\d+)/(?P<course_id>\d+)/$', 'professors'),
	url(r'^(?P<department_id>\d+)/(?P<course_id>\d+)/(?P<professor_id>\d+)/$', 'questions'),
	url(r'^(?P<department_id>\d+)/(?P<course_id>\d+)/(?P<professor_id>\d+)/(?P<question_id>\d+)/$', 'answers'),
)

schoolgods/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', include('qanda.urls')),
	url(r'^home/', include('qanda.urls')),
	url(r'^admin/', include(admin.site.urls)),
)

qanda/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Department(models.Model):
	subject         = models.CharField(max_length = 25)
	pub_date        = models.DateTimeField(auto_now_add = True)
	
	def __unicode__(self):
		return self.subject
		
class Course(models.Model):
	department      = models.ForeignKey(Department)
	number          = models.CharField(max_length = 50)
	name            = models.CharField(max_length = 100, blank = True, null = True)
	pub_date        = models.DateTimeField(auto_now_add = True)
	
	def __unicode__(self):
		return self.number
	
class Professor(models.Model):
	course          = models.ForeignKey(Course)
	name            = models.CharField(max_length = 50)
	pub_date        = models.DateTimeField(auto_now_add = True)
	
	def __unicode__(self):
		return self.name
	
class Question(models.Model):
	professor       = models.ForeignKey(Professor, blank = True, null = True)
	question_text   = models.CharField(max_length = 500)
	question_detail = models.CharField(max_length = 1000)
	q_pub_date      = models.DateTimeField(auto_now_add = True)
	q_author        = models.ForeignKey(User)
	
	def __unicode__(self):
		return self.question_text
		
class Answer(models.Model):
	question        = models.ForeignKey(Question, blank = True, null = True)
	answer_text     = models.CharField(max_length = 10000)
	a_pub_date      = models.DateTimeField(auto_now_add = True)
	a_author        = models.ForeignKey(User)
	
	def __unicode__(self):
		return self.answer_text
	

qanda/views.py
from django.http import HttpResponse
from qanda.models import Department, Course, Professor, Question, Answer
from django.shortcuts import render_to_response

def index(request):
	a     = Department.objects.all()
	b     = Course.objects.all()
	c     = Professor.objects.all()
	return render_to_response('qanda/index.html', {'departments': a, 'courses': b, 'professors':c})
	
def courses(request, department_id):	
	a = Department.objects.get(pk = department_id)
	b = Course.objects.filter(department = a)
	return render_to_response('qanda/courses.html', {'department':a,'courses':b})
	
def professors(request, department_id, course_id):
	a = Department.objects.get(pk = department_id)
	b = Course.objects.filter(department = a)
	c = Course.objects.get(pk = course_id)
	d = Professor.objects.filter(course = course_id)
	return render_to_response('qanda/professors.html', {'department':a, 'course':b, 'course':c, 'professors':d})
	
def questions(request, department_id, course_id, professor_id):
	a = Department.objects.get(pk = department_id)
	b = Course.objects.filter(department = a)
	c = Course.objects.get(pk = course_id)
	d = Professor.objects.filter(course = course_id)
	e = Professor.objects.get(pk = professor_id)
	f = Question.objects.filter(professor = professor_id)
	return render_to_response('qanda/questions.html', {'department':a, 'course':b, 'course':c, 'professor':d, 'professor':e, 'questions':f})
	
def answers(request, department_id, course_id, professor_id, question_id):
	a = Department.objects.get(pk = department_id)
	b = Course.objects.filter(department = a)
	c = Course.objects.get(pk = course_id)
	d = Professor.objects.filter(course = course_id)
	e = Professor.objects.get(pk = professor_id)
	f = Question.objects.filter(professor = professor_id)
	g = Question.objects.get(pk = question_id)
	h = Answer.objects.filter(question = question_id)
	return render_to_response('qanda/answers.html', {'department':a, 'course':b, 'course':c, 'professor':d, 'professor':e, 'question':f, 'question':g, 'answers':h})	
	

templates/handler500.html
<html>
<head>
<link rel="stylesheet" type="text/css" href="https://s3.amazonaws.com/mrt-static/static/css/base.css">
<link rel="stylesheet" type="text/css" href="https://s3.amazonaws.com/mrt-static/static/css/button.css">
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600' rel='stylesheet' type='text/css'>

<title>Movie Roundtable</title>
</head>

<body>
<div class="fullwrapper"></div>
<div class="header">
	<ul id="logo">
		<li><a href="/home/"><img src="http://i.imgur.com/8ScAe.jpg"></img></a></li>
	</ul>
	<ul id="navigation">
			{% if user.is_authenticated %}
				<p> Welcome back, {{ user.username }}! </p>
			{% else %}
				<li><a href="/home/register/">Register</a></li>
				<li> | </li>
				<li><a href="/home/accounts/login/">Sign In</a></li>
			{% endif %}
	</ul>
</div>

<div class="loggedOutPage">
<h1><span style="padding-left:30%;color:black;margin-top:100px;"></span></h1>

<span style="font-size:32px; padding-left:42.5%;"><a href = "/home/">Something's up with our servers. We're working hard to fix it!</a></span>
</div>

templates/qanda/answers.html
<html>

<h1><a href = "/home/"> Schoolgods </a></h1>

<h2><a href = "/home/{{ department.id }}/">{{ department.subject }}</a></h2>
<h3><a href = "/home/{{ department.id }}/{{ course.id }}/">{{ course.department }} {{ course.number }} {{ course.name }}</a></h3>
<h4><a href = "/home/{{ department.id }}/{{ course.id }}/{{ professor.id }}">{{ professor.name }}</a></h4>
<h5><a href = "/home/{{ department.id }}/{{ course.id }}/{{ professor.id }}/{{ question.id }}">{{ question.question_text }}</a></h5>


{% if answers %}
    <ul>
    {% for answer in answers %}
        <li><a href=#>{{ answer.answer_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Noone has answered.</p>
{% endif %}

</body>

</html>

templates/qanda/courses.html
<html>

<h1> <a href = "/home/">Schoolgods</a></h1>

<h2><a href = "/home/{{ department.id }}">{{ department.subject }}</a></h2>

{% if courses %}
    <ul>
    {% for course in courses %}
        <li><a href="/home/{{ department.id }}/{{ course.id }}/">{{ course.department }} {{ course.number }} {{ course.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No classes are available.</p>
{% endif %}

</body>

</html>

templates/qanda/index.html
<!-- test 
<html>

<h1> <a href = "/home/">Schoolgods</a></h1>

{% if departments %}
    <ul>
    {% for department in departments %}
        <li><a href="/home/{{ department.id }}/">{{ department.subject }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No classes are available.</p>
{% endif %}
-->
<!DOCTYPE html>
<html lang="en">
<head>
	<title>School Gods - The Ultimate Note Sharing Platform</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}static/js/jQuery.jGlideMenu.067.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}static/js/base.js"></script>
<script type="text/javascript">
		$(document).ready(function(){
			// Initialize Menu
			$('#jGlide_001').jGlideMenu({
				tileSource	: '.jGlide_001_tiles' , 
				demoMode	: true 
			}).show();

			// Connect "Toggle" Link	
			$('#switch').click(function(){$(this).jGlideMenuToggle();});
		});
</script>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}static/css/scaffolding.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}static/css/index.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}static/css/button.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}static/css/jGlideMenu.css" />

</head>
<body>
<div class="fullwrapper">
<div class="container">
	<div class="navigation">
	<div class="row">
		<div class="span4">
			<div class="logo">
				<a href="#"><img src="img/schoolgods_logo.gif"></img></a>
			</div>
		</div>
		<div class="signin">
		<div class="span3">

					Username:<input type="text" placeholder="Email">
		</div>	
		<div class="span3">		
					Password:<input type="text" placeholder="Password">
		</div>			
		<div class="span1">		
					<input type="submit" value="Sign In" class="btn-small btn-inverse">

		</div>
		</div>

		<div class="register">
			<div class="row">
				<div class="span3 offset1">		
					<a href="#" class="forgotPassword">Forgot your password?</a>
				</div>			
				<div class="span1">		
					<div id="registerButton">		
						<a href="registration.html"><input type="submit" value="Register" class="btn-small btn-inverse"></a>
					</div>
				</div>
			</div>	
		</div>	
		

	</div>
	</div>


<!-- Menu Holder -->
<div class="row">
	<div class="span9 offset4">
		<div class="jGM_box" id="jGlide_001">
			<!-- Tiles for Menu -->
			<ul id="tile_001" class="jGlide_001_tiles" title="Choose course below" alt="Select your class below">
				{% for department in departments %}
					<li rel = "department_{{ department.id }}">{{ department.subject }}</li>
				{% endfor %}
					<li rel = "1"> Test </li>
			</ul>
			
			{% regroup courses by departments as department_list %}
			
			{% for department in department_list %}
				<ul id = "department_{{ department.id }}" class = "jGlide_001_tiles" title = "Choose class" alt = "Choose your class now">
					{% for course in department_list %}
						<li rel = "course_{{ course.id }}">{{ course.number }} {{ course.name }}</li>
					{% endfor %}
				</ul>
			{% endfor %}
			
			<ul id = "1">
				<li rel = #> Test 2</li>
			</ul>
			
			{% regroup professors by courses as course_list %}
			
			{% for course in course_list %}
				<ul id = "course_{{ course.id }}">
					{% for professor in course_list %}
						<li rel = #>{{ professor.name }} </li>
					{% endfor %}
				</ul>
			{% endfor %}
			
		</div>
	</div>
</div>
</div>
</div>

</body>

</html>

templates/qanda/professors.html
<html>

<h1><a href = "/home/"> Schoolgods </a></h1>

<h2><a href = "/home/{{ department.id }}/">{{ department.subject }}</a></h2>
<h3><a href = "/home/{{ department.id }}/{{ course.id }}/">{{ course.department }} {{ course.number }} {{ course.name }}</a></h3>


{% if professors %}
    <ul>
    {% for professor in professors %}
        <li><a href="/home/{{ department.id }}/{{ course.id }}/{{ professor.id }}/">{{ professor.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No classes are available.</p>
{% endif %}

</body>

</html>

templates/qanda/questions.html
<html>

<h1><a href = "/home/"> Schoolgods </a></h1>

<h2><a href = "/home/{{ department.id }}/">{{ department.subject }}</a></h2>
<h3><a href = "/home/{{ department.id }}/{{ course.id }}/">{{ course.department }} {{ course.number }} {{ course.name }}</a></h3>
<h4><a href = "/home/{{ department.id }}/{{ course.id }}/{{ professor.id }}">{{ professor.name }}</a></h4>

{% if questions %}
    <ul>
    {% for question in questions %}
        <li><a href="/home/{{ department.id }}/{{ course.id }}/{{ professor.id }}/{{ question.id }}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No questions have been asked.</p>
{% endif %}

</body>

</html>